protocol file
ext py,go,ts,tsx,js,jsx,lua,fish,nix,md,sh,rs
action launch --type=tab --title ${FILE} -- nvim ${FILE_PATH}

protocol file
ext log
action launch --type=tab --title ${FILE} -- tail -f -- ${FILE_PATH}
